[2024-12-29T11:21:37.577+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:16:35.514341+00:00 [queued]>
[2024-12-29T11:21:37.584+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:16:35.514341+00:00 [queued]>
[2024-12-29T11:21:37.584+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-29T11:21:37.594+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-12-29 11:16:35.514341+00:00
[2024-12-29T11:21:37.598+0000] {standard_task_runner.py:57} INFO - Started process 68 to run task
[2024-12-29T11:21:37.601+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_teams', 'run_spark_job', 'manual__2024-12-29T11:16:35.514341+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_postgres_teams_dag.py', '--cfg-path', '/tmp/tmpxfianowf']
[2024-12-29T11:21:37.602+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask run_spark_job
[2024-12-29T11:21:37.644+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:16:35.514341+00:00 [running]> on host 3715022b59e4
[2024-12-29T11:21:37.704+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_teams' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T11:16:35.514341+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T11:16:35.514341+00:00'
[2024-12-29T11:21:37.705+0000] {logging_mixin.py:150} INFO - SSH connection closed
[2024-12-29T11:21:37.705+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_postgres_teams_dag.py", line 38, in run_spark_job
    password="developer"
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1
[2024-12-29T11:21:37.712+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_kafka_to_postgres_teams, task_id=run_spark_job, execution_date=20241229T111635, start_date=20241229T112137, end_date=20241229T112137
[2024-12-29T11:21:37.720+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 39 for task run_spark_job ([Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1; 68)
[2024-12-29T11:21:37.743+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-29T11:21:37.753+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
