[2025-01-05T20:43:24.063+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T20:43:23.093595+00:00 [queued]>
[2025-01-05T20:43:24.072+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T20:43:23.093595+00:00 [queued]>
[2025-01-05T20:43:24.072+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-01-05T20:43:24.081+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-01-05 20:43:23.093595+00:00
[2025-01-05T20:43:24.086+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2025-01-05T20:43:24.088+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_dag', 'submit_spark_job', 'manual__2025-01-05T20:43:23.093595+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/teams_kafka_to_spark.py', '--cfg-path', '/tmp/tmpjd9bp463']
[2025-01-05T20:43:24.090+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask submit_spark_job
[2025-01-05T20:43:24.132+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T20:43:23.093595+00:00 [running]> on host 3af9f4f70605
[2025-01-05T20:43:24.380+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_dag' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T20:43:23.093595+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T20:43:23.093595+00:00'
[2025-01-05T20:43:24.387+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-01-05T20:43:24.387+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook = self._get_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 190, in _get_hook
    spark_binary=self._spark_binary,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 154, in __init__
    self._connection = self._resolve_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 210, in _resolve_connection
    "The `spark-home` extra is not allowed any more. Please make sure one of"
RuntimeError: The `spark-home` extra is not allowed any more. Please make sure one of ['spark-submit', 'spark2-submit', 'spark3-submit'] is available on the PATH, and set `spark-binary` if needed.
[2025-01-05T20:43:24.393+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_kafka_to_postgres_dag, task_id=submit_spark_job, execution_date=20250105T204323, start_date=20250105T204324, end_date=20250105T204324
[2025-01-05T20:43:24.400+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 42 for task submit_spark_job (The `spark-home` extra is not allowed any more. Please make sure one of ['spark-submit', 'spark2-submit', 'spark3-submit'] is available on the PATH, and set `spark-binary` if needed.; 63)
[2025-01-05T20:43:24.441+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-05T20:43:24.458+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
