[2024-12-29T11:24:29.784+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:24:29.053347+00:00 [queued]>
[2024-12-29T11:24:29.790+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:24:29.053347+00:00 [queued]>
[2024-12-29T11:24:29.790+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-29T11:24:29.801+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-12-29 11:24:29.053347+00:00
[2024-12-29T11:24:29.809+0000] {standard_task_runner.py:57} INFO - Started process 70 to run task
[2024-12-29T11:24:29.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_teams', 'run_spark_job', 'manual__2024-12-29T11:24:29.053347+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_postgres_teams_dag.py', '--cfg-path', '/tmp/tmp277aoyvf']
[2024-12-29T11:24:29.814+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask run_spark_job
[2024-12-29T11:24:29.855+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:24:29.053347+00:00 [running]> on host 3715022b59e4
[2024-12-29T11:24:29.912+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_teams' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T11:24:29.053347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T11:24:29.053347+00:00'
[2024-12-29T11:24:30.303+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_9.8)
[2024-12-29T11:24:32.398+0000] {transport.py:1893} INFO - Authentication (password) failed.
[2024-12-29T11:24:32.400+0000] {logging_mixin.py:150} INFO - SSH connection closed
[2024-12-29T11:24:32.401+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_postgres_teams_dag.py", line 38, in run_spark_job
    password="developer"
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/client.py", line 496, in connect
    passphrase,
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/client.py", line 805, in _auth
    self._transport.auth_password(username, password)
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/transport.py", line 1587, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/auth_handler.py", line 263, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
[2024-12-29T11:24:32.420+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_kafka_to_postgres_teams, task_id=run_spark_job, execution_date=20241229T112429, start_date=20241229T112429, end_date=20241229T112432
[2024-12-29T11:24:32.434+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 40 for task run_spark_job (Authentication failed.; 70)
[2024-12-29T11:24:32.467+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-29T11:24:32.485+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
