[2025-01-07T15:49:05.345+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_ns.ingest_players manual__2025-01-07T15:48:58.994657+00:00 [queued]>
[2025-01-07T15:49:05.375+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_ns.ingest_players manual__2025-01-07T15:48:58.994657+00:00 [queued]>
[2025-01-07T15:49:05.378+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-01-07T15:49:05.432+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_players> on 2025-01-07 15:48:58.994657+00:00
[2025-01-07T15:49:05.444+0000] {standard_task_runner.py:57} INFO - Started process 3428 to run task
[2025-01-07T15:49:05.454+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_ns', 'ingest_players', 'manual__2025-01-07T15:48:58.994657+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/app_start_ns.py', '--cfg-path', '/tmp/tmpxqrrhra_']
[2025-01-07T15:49:05.457+0000] {standard_task_runner.py:85} INFO - Job 490: Subtask ingest_players
[2025-01-07T15:49:05.585+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_data_pipeline_ns.ingest_players manual__2025-01-07T15:48:58.994657+00:00 [running]> on host 27ff283f09fe
[2025-01-07T15:49:05.770+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_ns' AIRFLOW_CTX_TASK_ID='ingest_players' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T15:48:58.994657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T15:48:58.994657+00:00'
[2025-01-07T15:49:07.322+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/app_start_ns.py", line 68, in ingest_players
    subprocess.run(["python", "/opt/airflow/include/scripts/csv_to_postgres_players.py"], check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '/opt/airflow/include/scripts/csv_to_postgres_players.py']' returned non-zero exit status 1.
[2025-01-07T15:49:07.347+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_ns, task_id=ingest_players, execution_date=20250107T154858, start_date=20250107T154905, end_date=20250107T154907
[2025-01-07T15:49:07.371+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 490 for task ingest_players (Command '['python', '/opt/airflow/include/scripts/csv_to_postgres_players.py']' returned non-zero exit status 1.; 3428)
[2025-01-07T15:49:07.414+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-07T15:49:07.497+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
