[2025-01-06T16:04:10.833+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.kafka_retrieve_teams manual__2025-01-06T16:04:07.045162+00:00 [queued]>
[2025-01-06T16:04:10.841+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.kafka_retrieve_teams manual__2025-01-06T16:04:07.045162+00:00 [queued]>
[2025-01-06T16:04:10.841+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-01-06T16:04:10.849+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): kafka_retrieve_teams> on 2025-01-06 16:04:07.045162+00:00
[2025-01-06T16:04:10.854+0000] {standard_task_runner.py:57} INFO - Started process 3381 to run task
[2025-01-06T16:04:10.856+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'kafka_retrieve_teams', 'manual__2025-01-06T16:04:07.045162+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/full_nba_data_pipeline.py', '--cfg-path', '/tmp/tmp2n267471']
[2025-01-06T16:04:10.858+0000] {standard_task_runner.py:85} INFO - Job 305: Subtask kafka_retrieve_teams
[2025-01-06T16:04:10.892+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_data_pipeline.kafka_retrieve_teams manual__2025-01-06T16:04:07.045162+00:00 [running]> on host d37d09639978
[2025-01-06T16:04:10.943+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='kafka_retrieve_teams' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T16:04:07.045162+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T16:04:07.045162+00:00'
[2025-01-06T16:06:37.572+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-06T16:06:37.585+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 3381. PIDs of all processes in the group: [3381]
[2025-01-06T16:06:37.585+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 3381
[2025-01-06T16:07:37.594+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=3381, name='airflow task ru', status='sleeping', started='16:04:10') did not respond to SIGTERM. Trying SIGKILL
[2025-01-06T16:07:37.610+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 3381
[2025-01-06T16:07:37.635+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3381, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:04:10') (3381) terminated with exit code Negsignal.SIGKILL
[2025-01-06T16:07:37.636+0000] {standard_task_runner.py:174} ERROR - Job 305 was killed before it finished (likely due to running out of memory)
