[2024-12-29T11:11:29.755+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:11:28.179038+00:00 [queued]>
[2024-12-29T11:11:29.763+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:11:28.179038+00:00 [queued]>
[2024-12-29T11:11:29.763+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-29T11:11:29.773+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-12-29 11:11:28.179038+00:00
[2024-12-29T11:11:29.780+0000] {standard_task_runner.py:57} INFO - Started process 64 to run task
[2024-12-29T11:11:29.788+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_teams', 'run_spark_job', 'manual__2024-12-29T11:11:28.179038+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_postgres_teams_dag.py', '--cfg-path', '/tmp/tmpcewtj1p3']
[2024-12-29T11:11:29.795+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask run_spark_job
[2024-12-29T11:11:29.836+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T11:11:28.179038+00:00 [running]> on host 3715022b59e4
[2024-12-29T11:11:29.887+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_teams' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T11:11:28.179038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T11:11:28.179038+00:00'
[2024-12-29T11:11:29.889+0000] {logging_mixin.py:150} INFO - SSH connection closed
[2024-12-29T11:11:29.889+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_postgres_teams_dag.py", line 38, in run_spark_job
    password="developer"
  File "/home/airflow/.local/lib/python3.7/site-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1
[2024-12-29T11:11:29.897+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_kafka_to_postgres_teams, task_id=run_spark_job, execution_date=20241229T111128, start_date=20241229T111129, end_date=20241229T111129
[2024-12-29T11:11:29.907+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 37 for task run_spark_job ([Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1; 64)
[2024-12-29T11:11:29.936+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-29T11:11:29.949+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
