[2025-01-05T20:46:28.259+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T20:46:27.309509+00:00 [queued]>
[2025-01-05T20:46:28.266+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T20:46:27.309509+00:00 [queued]>
[2025-01-05T20:46:28.266+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-01-05T20:46:28.275+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-01-05 20:46:27.309509+00:00
[2025-01-05T20:46:28.279+0000] {standard_task_runner.py:57} INFO - Started process 56 to run task
[2025-01-05T20:46:28.282+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_dag', 'submit_spark_job', 'manual__2025-01-05T20:46:27.309509+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/teams_kafka_to_spark.py', '--cfg-path', '/tmp/tmp3kodi00o']
[2025-01-05T20:46:28.285+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask submit_spark_job
[2025-01-05T20:46:28.321+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_dag.submit_spark_job manual__2025-01-05T20:46:27.309509+00:00 [running]> on host 3af9f4f70605
[2025-01-05T20:46:28.556+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_dag' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T20:46:27.309509+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T20:46:27.309509+00:00'
[2025-01-05T20:46:28.561+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-01-05T20:46:28.562+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook = self._get_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 190, in _get_hook
    spark_binary=self._spark_binary,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 154, in __init__
    self._connection = self._resolve_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 203, in _resolve_connection
    f"The spark-binary extra can be on of {ALLOWED_SPARK_BINARIES} and it"
RuntimeError: The spark-binary extra can be on of ['spark-submit', 'spark2-submit', 'spark3-submit'] and it was `/opt/spark/bin/spark-submit`. Please make sure your spark binary is one of the allowed ones and that it is available on the PATH
[2025-01-05T20:46:28.567+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_kafka_to_postgres_dag, task_id=submit_spark_job, execution_date=20250105T204627, start_date=20250105T204628, end_date=20250105T204628
[2025-01-05T20:46:28.573+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 43 for task submit_spark_job (The spark-binary extra can be on of ['spark-submit', 'spark2-submit', 'spark3-submit'] and it was `/opt/spark/bin/spark-submit`. Please make sure your spark binary is one of the allowed ones and that it is available on the PATH; 56)
[2025-01-05T20:46:28.590+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-05T20:46:28.605+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
