[2024-12-29T12:37:27.162+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T12:32:12.266786+00:00 [queued]>
[2024-12-29T12:37:27.187+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T12:32:12.266786+00:00 [queued]>
[2024-12-29T12:37:27.188+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-29T12:37:27.214+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-12-29 12:32:12.266786+00:00
[2024-12-29T12:37:27.235+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2024-12-29T12:37:27.242+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_teams', 'run_spark_job', 'manual__2024-12-29T12:32:12.266786+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_postgres_teams_dag.py', '--cfg-path', '/tmp/tmpbp8_3xy_']
[2024-12-29T12:37:27.244+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask run_spark_job
[2024-12-29T12:37:27.343+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T12:32:12.266786+00:00 [running]> on host 01b022c2ce4f
[2024-12-29T12:37:27.500+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_teams' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T12:32:12.266786+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T12:32:12.266786+00:00'
[2024-12-29T12:37:27.807+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_9.0p1)
[2024-12-29T12:37:28.339+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-12-29T12:37:28.341+0000] {logging_mixin.py:150} INFO - SSH connection established.
[2024-12-29T12:37:29.395+0000] {logging_mixin.py:150} INFO - Spark job error output:
bash: line 1: /opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit: No such file or directory
[2024-12-29T12:37:29.398+0000] {logging_mixin.py:150} INFO - An error occurred: Spark job failed with error:
bash: line 1: /opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit: No such file or directory
[2024-12-29T12:37:29.411+0000] {logging_mixin.py:150} INFO - SSH connection closed.
[2024-12-29T12:37:29.421+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_to_postgres_teams_dag.py", line 49, in run_spark_job
    raise RuntimeError(f"Spark job failed with error:\n{stderr_output}")
RuntimeError: Spark job failed with error:
bash: line 1: /opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit: No such file or directory

[2024-12-29T12:37:29.648+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_kafka_to_postgres_teams, task_id=run_spark_job, execution_date=20241229T123212, start_date=20241229T123727, end_date=20241229T123729
[2024-12-29T12:37:29.737+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 57 for task run_spark_job (Spark job failed with error:
bash: line 1: /opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit: No such file or directory
; 65)
[2024-12-29T12:37:29.869+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-29T12:37:30.323+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
