[2025-01-07T15:49:07.451+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_ns.ingest_games manual__2025-01-07T15:48:58.994657+00:00 [queued]>
[2025-01-07T15:49:07.502+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_ns.ingest_games manual__2025-01-07T15:48:58.994657+00:00 [queued]>
[2025-01-07T15:49:07.503+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-01-07T15:49:07.542+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_games> on 2025-01-07 15:48:58.994657+00:00
[2025-01-07T15:49:07.549+0000] {standard_task_runner.py:57} INFO - Started process 3467 to run task
[2025-01-07T15:49:07.558+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_ns', 'ingest_games', 'manual__2025-01-07T15:48:58.994657+00:00', '--job-id', '493', '--raw', '--subdir', 'DAGS_FOLDER/app_start_ns.py', '--cfg-path', '/tmp/tmpd52jl_l6']
[2025-01-07T15:49:07.563+0000] {standard_task_runner.py:85} INFO - Job 493: Subtask ingest_games
[2025-01-07T15:49:07.628+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_data_pipeline_ns.ingest_games manual__2025-01-07T15:48:58.994657+00:00 [running]> on host 27ff283f09fe
[2025-01-07T15:49:07.733+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_ns' AIRFLOW_CTX_TASK_ID='ingest_games' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T15:48:58.994657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T15:48:58.994657+00:00'
[2025-01-07T15:49:07.916+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/app_start_ns.py", line 72, in ingest_games
    subprocess.run(["python", "/opt/airflow/include/scripts/csv_to_postgres_games.py"], check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '/opt/airflow/include/scripts/csv_to_postgres_games.py']' returned non-zero exit status 1.
[2025-01-07T15:49:07.932+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_ns, task_id=ingest_games, execution_date=20250107T154858, start_date=20250107T154907, end_date=20250107T154907
[2025-01-07T15:49:07.945+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 493 for task ingest_games (Command '['python', '/opt/airflow/include/scripts/csv_to_postgres_games.py']' returned non-zero exit status 1.; 3467)
[2025-01-07T15:49:07.955+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-07T15:49:07.975+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
