[2025-01-20T10:49:12.774+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline2.fetch_and_process_games manual__2025-01-20T10:49:08.193632+00:00 [queued]>
[2025-01-20T10:49:12.790+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline2.fetch_and_process_games manual__2025-01-20T10:49:08.193632+00:00 [queued]>
[2025-01-20T10:49:12.793+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-01-20T10:49:12.812+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fetch_and_process_games> on 2025-01-20 10:49:08.193632+00:00
[2025-01-20T10:49:12.818+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2025-01-20T10:49:12.825+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline2', 'fetch_and_process_games', 'manual__2025-01-20T10:49:08.193632+00:00', '--job-id', '942', '--raw', '--subdir', 'DAGS_FOLDER/full_nba_data_pipeline.py', '--cfg-path', '/tmp/tmpu1ey3x7v']
[2025-01-20T10:49:12.829+0000] {standard_task_runner.py:85} INFO - Job 942: Subtask fetch_and_process_games
[2025-01-20T10:49:12.883+0000] {task_command.py:410} INFO - Running <TaskInstance: nba_data_pipeline2.fetch_and_process_games manual__2025-01-20T10:49:08.193632+00:00 [running]> on host 647452f46e61
[2025-01-20T10:49:13.177+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_data_pipeline2' AIRFLOW_CTX_TASK_ID='fetch_and_process_games' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T10:49:08.193632+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T10:49:08.193632+00:00'
[2025-01-20T10:49:13.178+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_nba_data_pipeline.py", line 144, in fetch_and_process_games
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "bootstrap_servers""}
[2025-01-20T10:49:13.186+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline2, task_id=fetch_and_process_games, execution_date=20250120T104908, start_date=20250120T104912, end_date=20250120T104913
[2025-01-20T10:49:13.199+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 942 for task fetch_and_process_games (KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "bootstrap_servers""}; 67)
[2025-01-20T10:49:13.213+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-01-20T10:49:13.354+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
