[2024-12-29T09:36:32.394+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T09:36:31.723088+00:00 [queued]>
[2024-12-29T09:36:32.402+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T09:36:31.723088+00:00 [queued]>
[2024-12-29T09:36:32.403+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-29T09:36:32.445+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_spark_job> on 2024-12-29 09:36:31.723088+00:00
[2024-12-29T09:36:32.450+0000] {standard_task_runner.py:57} INFO - Started process 61 to run task
[2024-12-29T09:36:32.453+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_kafka_to_postgres_teams', 'run_spark_job', 'manual__2024-12-29T09:36:31.723088+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/spark_kafka_to_postgres_teams.py', '--cfg-path', '/tmp/tmp28l1m1lh']
[2024-12-29T09:36:32.456+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask run_spark_job
[2024-12-29T09:36:32.565+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_kafka_to_postgres_teams.run_spark_job manual__2024-12-29T09:36:31.723088+00:00 [running]> on host 4ce54193df39
[2024-12-29T09:36:32.625+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_kafka_to_postgres_teams' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T09:36:31.723088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T09:36:31.723088+00:00'
[2024-12-29T09:36:32.641+0000] {logging_mixin.py:150} INFO - Spark job error output: /opt/spark-3.2.0-bin-hadoop3.2/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
/opt/spark-3.2.0-bin-hadoop3.2/bin/spark-class: line 96: CMD: bad array subscript
[2024-12-29T09:36:32.642+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/spark_kafka_to_postgres_teams.py", line 18, in run_spark_job
    result = subprocess.run(spark_command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit', '--master', 'local[*]', '--packages', 'org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0,org.postgresql:postgresql:42.6.0', '/opt/airflow/dags/spark_jobs/kafka_to_postgres_teams.py']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spark_kafka_to_postgres_teams.py", line 22, in run_spark_job
    raise RuntimeError(f"Spark job failed with error: {e}")
RuntimeError: Spark job failed with error: Command '['/opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit', '--master', 'local[*]', '--packages', 'org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0,org.postgresql:postgresql:42.6.0', '/opt/***/dags/spark_jobs/kafka_to_postgres_teams.py']' returned non-zero exit status 1.
[2024-12-29T09:36:32.650+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_kafka_to_postgres_teams, task_id=run_spark_job, execution_date=20241229T093631, start_date=20241229T093632, end_date=20241229T093632
[2024-12-29T09:36:32.659+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 25 for task run_spark_job (Spark job failed with error: Command '['/opt/spark-3.2.0-bin-hadoop3.2/bin/spark-submit', '--master', 'local[*]', '--packages', 'org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0,org.postgresql:postgresql:42.6.0', '/opt/***/dags/spark_jobs/kafka_to_postgres_teams.py']' returned non-zero exit status 1.; 61)
[2024-12-29T09:36:32.677+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-29T09:36:32.692+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
